/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AideRouteImport } from './routes/aide'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BoutiquesRouteImport } from './routes/boutiques'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CommanderRouteImport } from './routes/commander'
import { Route as DevenirVendeurRouteImport } from './routes/devenir-vendeur'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as PolitiqueDeConfidentialiteRouteImport } from './routes/politique-de-confidentialite'
import { Route as RechercheRouteImport } from './routes/recherche'
import { Route as SuiviRouteImport } from './routes/suivi'
import { Route as VendreRouteImport } from './routes/vendre'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCompteRouteImport } from './routes/_authenticated/compte'
import { Route as AuthenticatedLivreurRouteImport } from './routes/_authenticated/livreur'
import { Route as AuthenticatedVendeurRouteImport } from './routes/_authenticated/vendeur'
import { Route as BoutiqueSlugRouteImport } from './routes/boutique.$slug'
import { Route as CategorieSlugRouteImport } from './routes/categorie.$slug'
import { Route as ProduitSlugRouteImport } from './routes/produit.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AideRoute = AideRouteImport.update({
  id: '/aide',
  path: '/aide',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiquesRoute = BoutiquesRouteImport.update({
  id: '/boutiques',
  path: '/boutiques',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CommanderRoute = CommanderRouteImport.update({
  id: '/commander',
  path: '/commander',
  getParentRoute: () => rootRouteImport,
} as any)
const DevenirVendeurRoute = DevenirVendeurRouteImport.update({
  id: '/devenir-vendeur',
  path: '/devenir-vendeur',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiqueDeConfidentialiteRoute =
  PolitiqueDeConfidentialiteRouteImport.update({
    id: '/politique-de-confidentialite',
    path: '/politique-de-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const RechercheRoute = RechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => rootRouteImport,
} as any)
const SuiviRoute = SuiviRouteImport.update({
  id: '/suivi',
  path: '/suivi',
  getParentRoute: () => rootRouteImport,
} as any)
const VendreRoute = VendreRouteImport.update({
  id: '/vendre',
  path: '/vendre',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompteRoute = AuthenticatedCompteRouteImport.update({
  id: '/compte',
  path: '/compte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLivreurRoute = AuthenticatedLivreurRouteImport.update({
  id: '/livreur',
  path: '/livreur',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendeurRoute = AuthenticatedVendeurRouteImport.update({
  id: '/vendeur',
  path: '/vendeur',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BoutiqueSlugRoute = BoutiqueSlugRouteImport.update({
  id: '/boutique/$slug',
  path: '/boutique/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorieSlugRoute = CategorieSlugRouteImport.update({
  id: '/categorie/$slug',
  path: '/categorie/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitSlugRoute = ProduitSlugRouteImport.update({
  id: '/produit/$slug',
  path: '/produit/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aide': typeof AideRoute
  '/auth': typeof AuthRoute
  '/boutiques': typeof BoutiquesRoute
  '/categories': typeof CategoriesRoute
  '/commander': typeof CommanderRoute
  '/devenir-vendeur': typeof DevenirVendeurRoute
  '/panier': typeof PanierRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/recherche': typeof RechercheRoute
  '/suivi': typeof SuiviRoute
  '/vendre': typeof VendreRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/compte': typeof AuthenticatedCompteRoute
  '/livreur': typeof AuthenticatedLivreurRoute
  '/vendeur': typeof AuthenticatedVendeurRoute
  '/boutique/$slug': typeof BoutiqueSlugRoute
  '/categorie/$slug': typeof CategorieSlugRoute
  '/produit/$slug': typeof ProduitSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aide': typeof AideRoute
  '/auth': typeof AuthRoute
  '/boutiques': typeof BoutiquesRoute
  '/categories': typeof CategoriesRoute
  '/commander': typeof CommanderRoute
  '/devenir-vendeur': typeof DevenirVendeurRoute
  '/panier': typeof PanierRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/recherche': typeof RechercheRoute
  '/suivi': typeof SuiviRoute
  '/vendre': typeof VendreRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/compte': typeof AuthenticatedCompteRoute
  '/livreur': typeof AuthenticatedLivreurRoute
  '/vendeur': typeof AuthenticatedVendeurRoute
  '/boutique/$slug': typeof BoutiqueSlugRoute
  '/categorie/$slug': typeof CategorieSlugRoute
  '/produit/$slug': typeof ProduitSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/aide': typeof AideRoute
  '/auth': typeof AuthRoute
  '/boutiques': typeof BoutiquesRoute
  '/categories': typeof CategoriesRoute
  '/commander': typeof CommanderRoute
  '/devenir-vendeur': typeof DevenirVendeurRoute
  '/panier': typeof PanierRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/recherche': typeof RechercheRoute
  '/suivi': typeof SuiviRoute
  '/vendre': typeof VendreRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/compte': typeof AuthenticatedCompteRoute
  '/_authenticated/livreur': typeof AuthenticatedLivreurRoute
  '/_authenticated/vendeur': typeof AuthenticatedVendeurRoute
  '/boutique/$slug': typeof BoutiqueSlugRoute
  '/categorie/$slug': typeof CategorieSlugRoute
  '/produit/$slug': typeof ProduitSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aide'
    | '/auth'
    | '/boutiques'
    | '/categories'
    | '/commander'
    | '/devenir-vendeur'
    | '/panier'
    | '/politique-de-confidentialite'
    | '/recherche'
    | '/suivi'
    | '/vendre'
    | '/admin'
    | '/compte'
    | '/livreur'
    | '/vendeur'
    | '/boutique/$slug'
    | '/categorie/$slug'
    | '/produit/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aide'
    | '/auth'
    | '/boutiques'
    | '/categories'
    | '/commander'
    | '/devenir-vendeur'
    | '/panier'
    | '/politique-de-confidentialite'
    | '/recherche'
    | '/suivi'
    | '/vendre'
    | '/admin'
    | '/compte'
    | '/livreur'
    | '/vendeur'
    | '/boutique/$slug'
    | '/categorie/$slug'
    | '/produit/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/aide'
    | '/auth'
    | '/boutiques'
    | '/categories'
    | '/commander'
    | '/devenir-vendeur'
    | '/panier'
    | '/politique-de-confidentialite'
    | '/recherche'
    | '/suivi'
    | '/vendre'
    | '/_authenticated/admin'
    | '/_authenticated/compte'
    | '/_authenticated/livreur'
    | '/_authenticated/vendeur'
    | '/boutique/$slug'
    | '/categorie/$slug'
    | '/produit/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AideRoute: typeof AideRoute
  AuthRoute: typeof AuthRoute
  BoutiquesRoute: typeof BoutiquesRoute
  CategoriesRoute: typeof CategoriesRoute
  CommanderRoute: typeof CommanderRoute
  DevenirVendeurRoute: typeof DevenirVendeurRoute
  PanierRoute: typeof PanierRoute
  PolitiqueDeConfidentialiteRoute: typeof PolitiqueDeConfidentialiteRoute
  RechercheRoute: typeof RechercheRoute
  SuiviRoute: typeof SuiviRoute
  VendreRoute: typeof VendreRoute
  BoutiqueSlugRoute: typeof BoutiqueSlugRoute
  CategorieSlugRoute: typeof CategorieSlugRoute
  ProduitSlugRoute: typeof ProduitSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aide': {
      id: '/aide'
      path: '/aide'
      fullPath: '/aide'
      preLoaderRoute: typeof AideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutiques': {
      id: '/boutiques'
      path: '/boutiques'
      fullPath: '/boutiques'
      preLoaderRoute: typeof BoutiquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commander': {
      id: '/commander'
      path: '/commander'
      fullPath: '/commander'
      preLoaderRoute: typeof CommanderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devenir-vendeur': {
      id: '/devenir-vendeur'
      path: '/devenir-vendeur'
      fullPath: '/devenir-vendeur'
      preLoaderRoute: typeof DevenirVendeurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-de-confidentialite': {
      id: '/politique-de-confidentialite'
      path: '/politique-de-confidentialite'
      fullPath: '/politique-de-confidentialite'
      preLoaderRoute: typeof PolitiqueDeConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recherche': {
      id: '/recherche'
      path: '/recherche'
      fullPath: '/recherche'
      preLoaderRoute: typeof RechercheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suivi': {
      id: '/suivi'
      path: '/suivi'
      fullPath: '/suivi'
      preLoaderRoute: typeof SuiviRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendre': {
      id: '/vendre'
      path: '/vendre'
      fullPath: '/vendre'
      preLoaderRoute: typeof VendreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compte': {
      id: '/_authenticated/compte'
      path: '/compte'
      fullPath: '/compte'
      preLoaderRoute: typeof AuthenticatedCompteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/livreur': {
      id: '/_authenticated/livreur'
      path: '/livreur'
      fullPath: '/livreur'
      preLoaderRoute: typeof AuthenticatedLivreurRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendeur': {
      id: '/_authenticated/vendeur'
      path: '/vendeur'
      fullPath: '/vendeur'
      preLoaderRoute: typeof AuthenticatedVendeurRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/boutique/$slug': {
      id: '/boutique/$slug'
      path: '/boutique/$slug'
      fullPath: '/boutique/$slug'
      preLoaderRoute: typeof BoutiqueSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorie/$slug': {
      id: '/categorie/$slug'
      path: '/categorie/$slug'
      fullPath: '/categorie/$slug'
      preLoaderRoute: typeof CategorieSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produit/$slug': {
      id: '/produit/$slug'
      path: '/produit/$slug'
      fullPath: '/produit/$slug'
      preLoaderRoute: typeof ProduitSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCompteRoute: typeof AuthenticatedCompteRoute
  AuthenticatedLivreurRoute: typeof AuthenticatedLivreurRoute
  AuthenticatedVendeurRoute: typeof AuthenticatedVendeurRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCompteRoute: AuthenticatedCompteRoute,
  AuthenticatedLivreurRoute: AuthenticatedLivreurRoute,
  AuthenticatedVendeurRoute: AuthenticatedVendeurRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AideRoute: AideRoute,
  AuthRoute: AuthRoute,
  BoutiquesRoute: BoutiquesRoute,
  CategoriesRoute: CategoriesRoute,
  CommanderRoute: CommanderRoute,
  DevenirVendeurRoute: DevenirVendeurRoute,
  PanierRoute: PanierRoute,
  PolitiqueDeConfidentialiteRoute: PolitiqueDeConfidentialiteRoute,
  RechercheRoute: RechercheRoute,
  SuiviRoute: SuiviRoute,
  VendreRoute: VendreRoute,
  BoutiqueSlugRoute: BoutiqueSlugRoute,
  CategorieSlugRoute: CategorieSlugRoute,
  ProduitSlugRoute: ProduitSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
